---
# tasks file for ansible-mysql57
#
- name: check mysql root passowrd is set
  assert:
    that:
      - "mysql_root_password is defined"
- name: check mysql root passowrd is not empty
  assert:
    that:
      - not mysql_root_password | bool
- name: check running on docker?
  shell: ls -l /.dockerenv | wc -l
  register: is_docker
  changed_when: no
- name: Include install packages
  include_tasks: install_centos7.yml
- name: Change default authentication plugin
  lineinfile:
    path: /etc/my.cnf
    regexp: '^ *default-authentication-plugin='
    line: 'default-authentication-plugin=mysql_native_password'
    state: present
- name: boot MySQL docker
  include_tasks: boot_docker_centos7.yml
  when: is_docker.stdout | bool
- name: boot MySQL systemd
  systemd:
    name: mysqld.service
    state: started
    enabled: yes
  when: not is_docker.stdout | bool
- name: get mysql initial root password
  shell: cat /var/log/mysqld.log | tail -1 |grep 'temporary password is generated for root'|cut -d '@' -f 2|cut -d ' ' -f 2
  register: mysqld_root_init_pass
  changed_when: no
- name: Change MySQL root user password
  shell: |
   mysql -u root -p'{{ mysqld_root_init_pass.stdout }}' --connect-expired-password -e "set password for root@'localhost'=password('{{ mysql_root_password }}');"
  register: root_password_change
  failed_when: false
  changed_when: false
- name: debug
  debug: var=root_password_change.stderr_lines
- name: set root .my.cnf
  template:
    src: root.my.cnf
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0644
  when: >
    (root_password_change.stderr_lines[1] is not defined) or 
    ("ERROR 1045 " in root_password_change.stderr_lines[1])
- name: Check MySQL root connection
  mysql_info:
    login_user: root
